
import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faBarcode,
    faBell,
    faBinoculars,
    faCalendarAlt,
    faChartLine,
    faCheck,
    faCircle,
    faCog,
    faCogs,
    faColumns,
    faCopy,
    faCubes,
    faDesktop,
    faEdit,
    faExclamationCircle,
    faExclamationTriangle,
    faFilter,
    faHeartbeat,
    faInfoCircle,
    faKey,
    faLink,
    faList,
    faLock,
    faLockOpen,
    faMinusSquare,
    faPlus,
    faPlusSquare,
    faPrint,
    faQuestionCircle,
    faSave,
    faSearch,
    faServer,
    faSpinner,
    faStar,
    faSyncAlt,
    faTools,
    faTrashAlt
} from '@fortawesome/free-solid-svg-icons';

library.add(faBarcode);
library.add(faBell);
library.add(faBinoculars);
library.add(faCalendarAlt);
library.add(faChartLine);
library.add(faCheck);
library.add(faCircle);
library.add(faCog);
library.add(faCogs);
library.add(faColumns);
library.add(faCopy);
library.add(faCubes);
library.add(faDesktop);
library.add(faEdit);
library.add(faExclamationCircle);
library.add(faExclamationTriangle);
library.add(faFilter);
library.add(faHeartbeat);
library.add(faInfoCircle);
library.add(faKey);
library.add(faLink);
library.add(faList);
library.add(faLock);
library.add(faLockOpen);
library.add(faMinusSquare);
library.add(faPlus);
library.add(faPlusSquare);
library.add(faPrint);
library.add(faQuestionCircle);
library.add(faSave);
library.add(faSearch);
library.add(faServer);
library.add(faSpinner);
library.add(faStar);
library.add(faSyncAlt);
library.add(faTools);
library.add(faTrashAlt);