
import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faAt,
    faBarcode,
    faBell,
    faBinoculars,
    faCalendarAlt,
    faChartBar,
    faChartLine,
    faCheck,
    faCircle,
    faClock,
    faCloudShowersHeavy,
    faCloudSun,
    faCloudSunRain,
    faCog,
    faCogs,
    faColumns,
    faCopy,
    faCubes,
    faDesktop,
    faEdit,
    faExclamationCircle,
    faExclamationTriangle,
    faFilter,
    faFont,
    faHashtag,
    faHeartbeat,
    faInfoCircle,
    faKey,
    faLink,
    faList,
    faListOl,
    faListUl,
    faLock,
    faLockOpen,
    faMemory,
    faMinusSquare,
    faNetworkWired,
    faPaintRoller,
    faPaperPlane,
    faPlay,
    faPlus,
    faPlusSquare,
    faPrint,
    faQuestionCircle,
    faSave,
    faSearch,
    faServer,
    faSms,
    faSpinner,
    faStar,
    faSun,
    faSyncAlt,
    faTasks,
    faTerminal,
    faTools,
    faTrashAlt,
    faUser,
    faUsers
} from '@fortawesome/free-solid-svg-icons';

library.add(faAt);
library.add(faBarcode);
library.add(faBell);
library.add(faBinoculars);
library.add(faCalendarAlt);
library.add(faChartBar);
library.add(faChartLine);
library.add(faCheck);
library.add(faCircle);
library.add(faClock);
library.add(faCloudShowersHeavy);
library.add(faCloudSun);
library.add(faCloudSunRain);
library.add(faCog);
library.add(faCogs);
library.add(faColumns);
library.add(faCopy);
library.add(faCubes);
library.add(faDesktop);
library.add(faEdit);
library.add(faExclamationCircle);
library.add(faExclamationTriangle);
library.add(faFilter);
library.add(faFont);
library.add(faHashtag);
library.add(faHeartbeat);
library.add(faInfoCircle);
library.add(faKey);
library.add(faLink);
library.add(faList);
library.add(faListOl);
library.add(faListUl);
library.add(faLock);
library.add(faLockOpen);
library.add(faMemory);
library.add(faMinusSquare);
library.add(faNetworkWired);
library.add(faPaintRoller);
library.add(faPaperPlane);
library.add(faPlay);
library.add(faPlus);
library.add(faPlusSquare);
library.add(faPrint);
library.add(faQuestionCircle);
library.add(faSave);
library.add(faSearch);
library.add(faServer);
library.add(faSms);
library.add(faSpinner);
library.add(faStar);
library.add(faSun);
library.add(faSyncAlt);
library.add(faTasks);
library.add(faTerminal);
library.add(faTools);
library.add(faTrashAlt);
library.add(faUser);
library.add(faUsers);